import type { FundCycle, Group, GroupExpense, Transaction, User } from "@/lib/types";

export const mockUser: User = {
  id: "u1",
  name: "Ram Sharma",
  email: "ram@example.com",
  avatarColor: "#1A6B5A",
  monthlyBudget: 45000,
  phone: "+977-9841234567",
  initials: "RS",
  paymentQR: { provider: "eSewa", name: "Ram Sharma" },
};

export const CURRENT_USER_ID = "u1";

export const mockGroups: Group[] = [
  {
    id: "sg1",
    name: "Flat 4B Shared Fund",
    avatarColor: "#1A6B5A",
    inviteCode: "SAJHA-4B12",
    leaderId: "u1",
    memberIds: ["u1", "u2", "u3", "u4"],
    targetDayOfMonth: 5,
    createdAt: "2025-06-14",
    memberCount: 4,
    balance: 0,
    lastUpdated: "2025-07-12",
  },
  {
    id: "g2",
    name: "Dashain Trip 2025",
    avatarColor: "#534AB7",
    inviteCode: "SAJHA-D25A",
    leaderId: "u2",
    memberIds: ["u1", "u2", "u3", "u4", "u5", "u6", "u7", "u8", "u9"],
    targetDayOfMonth: 10,
    createdAt: "2025-05-21",
    memberCount: 9,
    balance: 1200,
    lastUpdated: "2025-07-10",
  },
  {
    id: "g3",
    name: "Pokhara Crew",
    avatarColor: "#BA7517",
    inviteCode: "SAJHA-PK98",
    leaderId: "u3",
    memberIds: ["u1", "u3", "u4", "u5"],
    targetDayOfMonth: 15,
    createdAt: "2025-06-01",
    memberCount: 4,
    balance: 0,
    lastUpdated: "2025-07-08",
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: "t1",
    title: "Lunch at Bhojan Griha",
    amount: 850,
    type: "expense",
    category: "food",
    date: "2025-07-12",
    groupId: "g1",
  },
  {
    id: "t2",
    title: "Bus to Lakeside",
    amount: 45,
    type: "expense",
    category: "transport",
    date: "2025-07-11",
    groupId: "g3",
  },
  {
    id: "t3",
    title: "Salary received",
    amount: 55000,
    type: "income",
    category: "other",
    date: "2025-07-10",
  },
  {
    id: "t4",
    title: "Dal Bhat + Momo",
    amount: 380,
    type: "expense",
    category: "food",
    date: "2025-07-09",
    groupId: "g1",
  },
  {
    id: "t5",
    title: "Dashain contribution",
    amount: 5000,
    type: "expense",
    category: "other",
    date: "2025-07-08",
    groupId: "g2",
  },
];

export const mockCycle: FundCycle = {
  id: "c1",
  name: "Dashain Dhikuti",
  totalRounds: 10,
  currentRound: 3,
  contributionAmount: 5000,
  nextPayoutDate: "2025-08-01",
  nextRecipient: "Sita Rai",
};

export const mockSharedGroup = {
  id: "sg1",
  name: "Flat 4B Shared Fund",
  poolTotal: 20000,
  memberCount: 4,
  leaderId: "u1",
  members: [
    {
      id: "u1",
      name: "Aarav Sharma",
      initials: "AS",
      color: "#E1F5EE",
      role: "leader",
      contributed: 5000,
    },
    {
      id: "u2",
      name: "Sita Rai",
      initials: "SR",
      color: "#EEEDFE",
      role: "member",
      contributed: 5000,
    },
    {
      id: "u3",
      name: "Bibek Thapa",
      initials: "BT",
      color: "#FAEEDA",
      role: "member",
      contributed: 5000,
    },
    {
      id: "u4",
      name: "Priya Gurung",
      initials: "PG",
      color: "#FCEBEB",
      role: "member",
      contributed: 5000,
    },
  ],
};

export const mockGroupExpenses: GroupExpense[] = [
  {
    id: "ge1",
    groupId: "sg1",
    title: "Grocery — Bhatbhateni",
    amount: 2340,
    category: "food",
    date: "2025-07-12",
    addedAt: "2025-07-12T10:30:00Z",
    addedBy: "u1",
    addedByName: "Aarav Sharma",
    addedByInitials: "AS",
    addedByColor: "#E1F5EE",
  },
  {
    id: "ge2",
    groupId: "sg1",
    title: "Gas cylinder",
    amount: 1800,
    category: "other",
    date: "2025-07-11",
    addedAt: "2025-07-11T14:00:00Z",
    addedBy: "u2",
    addedByName: "Sita Rai",
    addedByInitials: "SR",
    addedByColor: "#EEEDFE",
  },
  {
    id: "ge3",
    groupId: "sg1",
    title: "Vegetables from bazaar",
    amount: 860,
    category: "food",
    date: "2025-07-11",
    addedAt: "2025-07-11T08:15:00Z",
    addedBy: "u3",
    addedByName: "Bibek Thapa",
    addedByInitials: "BT",
    addedByColor: "#FAEEDA",
    notes: "Fresh stock for the week",
  },
  {
    id: "ge4",
    groupId: "sg1",
    title: "House rent — July",
    amount: 8000,
    category: "rent",
    date: "2025-07-01",
    addedAt: "2025-07-01T09:00:00Z",
    addedBy: "u1",
    addedByName: "Aarav Sharma",
    addedByInitials: "AS",
    addedByColor: "#E1F5EE",
  },
  {
    id: "ge5",
    groupId: "sg1",
    title: "Bus — Lakeside trip",
    amount: 300,
    category: "transport",
    date: "2025-07-09",
    addedAt: "2025-07-09T17:00:00Z",
    addedBy: "u4",
    addedByName: "Priya Gurung",
    addedByInitials: "PG",
    addedByColor: "#FCEBEB",
  },
  {
    id: "ge6",
    groupId: "sg1",
    title: "Cleaning supplies",
    amount: 450,
    category: "shopping",
    date: "2025-07-08",
    addedAt: "2025-07-08T11:00:00Z",
    addedBy: "u2",
    addedByName: "Sita Rai",
    addedByInitials: "SR",
    addedByColor: "#EEEDFE",
  },
  {
    id: "ge7",
    groupId: "sg1",
    title: "Internet bill",
    amount: 1800,
    category: "other",
    date: "2025-07-05",
    addedAt: "2025-07-05T10:00:00Z",
    addedBy: "u3",
    addedByName: "Bibek Thapa",
    addedByInitials: "BT",
    addedByColor: "#FAEEDA",
  },
];

export const mockMembers = [
  {
    id: "u1",
    name: "Aarav Sharma",
    initials: "AS",
    paid: true,
  },
  {
    id: "u2",
    name: "Sita Rai",
    initials: "SR",
    paid: true,
  },
  {
    id: "u3",
    name: "Rohan Thapa",
    initials: "RT",
    paid: false,
  },
  {
    id: "u4",
    name: "Mina Koirala",
    initials: "MK",
    paid: false,
  },
];

export const mockAnalyticsSummary = {
  month: "July 2025",
  totalSpent: 28500,
  totalIncome: 73000,
  totalSaved: 44500,
  budget: 45000,
  daysLeft: 19,
  budgetUsed: 63,
};

export const mockDailySpending = [
  { day: "1", amount: 800 },
  { day: "2", amount: 2200 },
  { day: "3", amount: 450 },
  { day: "4", amount: 3100 },
  { day: "5", amount: 900 },
  { day: "6", amount: 200 },
  { day: "7", amount: 1800 },
  { day: "8", amount: 2500 },
  { day: "9", amount: 350 },
  { day: "10", amount: 4200 },
  { day: "11", amount: 1100 },
  { day: "12", amount: 2800 },
  { day: "13", amount: 300 },
  { day: "14", amount: 1600 },
  { day: "15", amount: 700 },
  { day: "16", amount: 3400 },
  { day: "17", amount: 1200 },
  { day: "18", amount: 2100 },
  { day: "19", amount: 500 },
  { day: "20", amount: 1500 },
];

export const mockCategorySpending = [
  { category: "food", amount: 9200 },
  { category: "rent", amount: 12000 },
  { category: "transport", amount: 3100 },
  { category: "shopping", amount: 4200 },
  { category: "health", amount: 800 },
  { category: "other", amount: 1200 },
];

export const mockAnalyticsTopExpenses = [
  {
    id: "ae1",
    title: "House rent",
    amount: 12000,
    type: "expense" as const,
    category: "rent" as const,
    date: "2025-07-01",
  },
  {
    id: "ae2",
    title: "Dal Bhat + Momo",
    amount: 4200,
    type: "expense" as const,
    category: "shopping" as const,
    date: "2025-07-14",
  },
  {
    id: "ae3",
    title: "Grocery",
    amount: 2340,
    type: "expense" as const,
    category: "food" as const,
    date: "2025-07-12",
  },
  {
    id: "ae4",
    title: "Internet",
    amount: 1800,
    type: "expense" as const,
    category: "other" as const,
    date: "2025-07-05",
  },
  {
    id: "ae5",
    title: "Vegetables",
    amount: 860,
    type: "expense" as const,
    category: "food" as const,
    date: "2025-07-11",
  },
];
