import type { Expense, Group, User } from "@/types";

export const demoUsers: User[] = [
  {
    id: "u1",
    name: "Ram Sharma",
    email: "ram@example.com",
    avatarColor: "#1A6B5A",
    paymentQR: { provider: "eSewa", name: "Ram Sharma" },
    monthlyBudget: 45000,
    phone: "+977-9841234567",
    initials: "RS",
  },
  {
    id: "u2",
    name: "Sita Rai",
    email: "sita@example.com",
    avatarColor: "#534AB7",
    monthlyBudget: 32000,
    initials: "SR",
  },
  {
    id: "u3",
    name: "Bibek Thapa",
    email: "bibek@example.com",
    avatarColor: "#BA7517",
    monthlyBudget: 30000,
    initials: "BT",
  },
  {
    id: "u4",
    name: "Priya Gurung",
    email: "priya@example.com",
    avatarColor: "#E24B4A",
    monthlyBudget: 28000,
    initials: "PG",
  },
  {
    id: "u5",
    name: "Rohan Shah",
    email: "rohan@example.com",
    avatarColor: "#185FA5",
    monthlyBudget: 25000,
    initials: "RS",
  },
  {
    id: "u6",
    name: "Mina Koirala",
    email: "mina@example.com",
    avatarColor: "#888780",
    monthlyBudget: 25000,
    initials: "MK",
  },
  {
    id: "u7",
    name: "Anisha Khatri",
    email: "anisha@example.com",
    avatarColor: "#5D6BCE",
    monthlyBudget: 26000,
    initials: "AK",
  },
  {
    id: "u8",
    name: "Sandeep KC",
    email: "sandeep@example.com",
    avatarColor: "#1D9E75",
    monthlyBudget: 26000,
    initials: "SK",
  },
  {
    id: "u9",
    name: "Nisha Sharma",
    email: "nisha@example.com",
    avatarColor: "#E24B4A",
    monthlyBudget: 26000,
    initials: "NS",
  },
];

export const demoGroups: Group[] = [
  {
    id: "g-flat4b",
    name: "Flat 4B Shared Fund",
    avatarColor: "#1A6B5A",
    inviteCode: "SAJHA-4B12",
    leaderId: "u1",
    memberIds: ["u1", "u2", "u3", "u4"],
    targetDayOfMonth: 5,
    paymentQR: { provider: "eSewa", name: "Flat 4B Fund" },
    createdAt: "2025-06-14",
    memberCount: 4,
    lastUpdated: "2025-07-23",
    statusText: "Settled up",
    balance: 0,
  },
  {
    id: "g-dashain",
    name: "Dashain Trip 2025",
    avatarColor: "#534AB7",
    inviteCode: "SAJHA-D25A",
    leaderId: "u2",
    memberIds: ["u1", "u2", "u3", "u4", "u5", "u6", "u7", "u8", "u9"],
    targetDayOfMonth: 10,
    paymentQR: { provider: "Bank", name: "Dashain Trip Wallet" },
    createdAt: "2025-05-21",
    memberCount: 9,
    lastUpdated: "2025-07-22",
    statusText: "They owe NPR 1,200",
    balance: 1200,
  },
  {
    id: "g-pokhara",
    name: "Pokhara Crew",
    avatarColor: "#BA7517",
    inviteCode: "SAJHA-PK98",
    leaderId: "u3",
    memberIds: ["u1", "u3", "u4", "u5"],
    targetDayOfMonth: 15,
    paymentQR: { provider: "eSewa", name: "Pokhara Crew Wallet" },
    createdAt: "2025-06-01",
    memberCount: 4,
    lastUpdated: "2025-07-20",
    statusText: "Settled up",
    balance: 0,
  },
];

export const demoExpenses: Expense[] = [
  {
    id: "e1",
    description: "House rent",
    title: "House rent",
    amount: 12000,
    category: "rent",
    date: "2025-07-01",
    paidById: "u1",
    groupId: "g-flat4b",
    splitType: "equal",
    splits: [
      { userId: "u1", amount: 3000 },
      { userId: "u2", amount: 3000 },
      { userId: "u3", amount: 3000 },
      { userId: "u4", amount: 3000 },
    ],
    createdAt: "2025-07-01T08:00:00Z",
  },
  {
    id: "e2",
    description: "Dal Bhat + Momo",
    title: "Dal Bhat + Momo",
    amount: 4200,
    category: "shopping",
    date: "2025-07-14",
    paidById: "u2",
    groupId: "g-dashain",
    splitType: "equal",
    splits: [{ userId: "u1", amount: 1400 }, { userId: "u2", amount: 1400 }, { userId: "u3", amount: 1400 }],
    createdAt: "2025-07-14T12:00:00Z",
  },
  {
    id: "e3",
    description: "Grocery",
    title: "Grocery",
    amount: 2340,
    category: "groceries",
    date: "2025-07-12",
    paidById: "u1",
    groupId: "g-flat4b",
    splitType: "equal",
    splits: [{ userId: "u1", amount: 780 }, { userId: "u2", amount: 780 }, { userId: "u3", amount: 780 }],
    createdAt: "2025-07-12T09:40:00Z",
  },
  {
    id: "e4",
    description: "Internet",
    title: "Internet",
    amount: 1800,
    category: "utilities",
    date: "2025-07-05",
    paidById: "u3",
    groupId: "g-flat4b",
    splitType: "equal",
    splits: [{ userId: "u1", amount: 600 }, { userId: "u2", amount: 600 }, { userId: "u3", amount: 600 }],
    createdAt: "2025-07-05T10:00:00Z",
  },
  {
    id: "e5",
    description: "Vegetables",
    title: "Vegetables",
    amount: 860,
    category: "food",
    date: "2025-07-11",
    paidById: "u4",
    groupId: "g-flat4b",
    splitType: "equal",
    splits: [{ userId: "u1", amount: 215 }, { userId: "u2", amount: 215 }, { userId: "u3", amount: 215 }, { userId: "u4", amount: 215 }],
    createdAt: "2025-07-11T08:15:00Z",
  },
  {
    id: "e6",
    description: "Bus to Lakeside",
    title: "Bus to Lakeside",
    amount: 300,
    category: "transport",
    date: "2025-07-09",
    paidById: "u5",
    groupId: "g-pokhara",
    splitType: "equal",
    splits: [{ userId: "u1", amount: 75 }, { userId: "u3", amount: 75 }, { userId: "u4", amount: 75 }, { userId: "u5", amount: 75 }],
    createdAt: "2025-07-09T17:00:00Z",
  },
  {
    id: "e7",
    description: "Cleaning supplies",
    title: "Cleaning supplies",
    amount: 450,
    category: "shopping",
    date: "2025-07-08",
    paidById: "u2",
    groupId: "g-flat4b",
    splitType: "equal",
    splits: [{ userId: "u1", amount: 150 }, { userId: "u2", amount: 150 }, { userId: "u3", amount: 150 }],
    createdAt: "2025-07-08T11:00:00Z",
  },
  {
    id: "e8",
    description: "Medicine",
    title: "Medicine",
    amount: 800,
    category: "health",
    date: "2025-07-16",
    paidById: "u6",
    groupId: "g-pokhara",
    splitType: "equal",
    splits: [{ userId: "u1", amount: 200 }, { userId: "u3", amount: 200 }, { userId: "u4", amount: 200 }, { userId: "u6", amount: 200 }],
    createdAt: "2025-07-16T14:30:00Z",
  },
];
